language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - composer require symfony/dom-crawler:dev-master symfony/css-selector:dev-master

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml --exclude=InterNations.Syntax.MethodTypeHints ./src/
  - ./vendor/bin/phpunit --exclude-group performance

cache:
  directories:
    - vendor/
